#############################################################################
# Makefile for building: glacier-settings
# Generated by qmake (3.0) (Qt 5.6.3)
# Project:  glacier-settings.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake 'QMAKE_CFLAGS_RELEASE=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -fmessage-length=0 -march=armv7-a -mfloat-abi=hard -mfpu=neon -mthumb -Wno-psabi' 'QMAKE_CFLAGS_DEBUG=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -fmessage-length=0 -march=armv7-a -mfloat-abi=hard -mfpu=neon -mthumb -Wno-psabi' 'QMAKE_CXXFLAGS_RELEASE=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -fmessage-length=0 -march=armv7-a -mfloat-abi=hard -mfpu=neon -mthumb -Wno-psabi' 'QMAKE_CXXFLAGS_DEBUG=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -fmessage-length=0 -march=armv7-a -mfloat-abi=hard -mfpu=neon -mthumb -Wno-psabi' QMAKE_STRIP=: PREFIX=/usr -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile glacier-settings.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -fmessage-length=0 -march=armv7-a -mfloat-abi=hard -mfpu=neon -mthumb -Wno-psabi -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -fmessage-length=0 -march=armv7-a -mfloat-abi=hard -mfpu=neon -mthumb -Wno-psabi -std=gnu++0x -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/libglacierapp -isystem /usr/include/mdeclarativecache5 -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtQuick -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtQml -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtCore -I. -I/usr/share/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = glacier-settings1.0.0
DISTDIR = /home/mersdk/share/nemo/settings/glacier-settings/.tmp/glacier-settings1.0.0
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS) -pie -rdynamic -lglacierapp -lmdeclarativecache5 -lQt5Quick -lQt5Gui -lQt5Qml -lQt5Network -lQt5Core -lGLESv2 -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = :

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/models/settingsmodel.cpp \
		src/models/imagesmodel.cpp \
		src/models/settingsproxymodel.cpp \
		certificates.cpp moc_settingsmodel.cpp \
		moc_imagesmodel.cpp \
		moc_settingsproxymodel.cpp \
		moc_certificates.cpp
OBJECTS       = main.o \
		settingsmodel.o \
		imagesmodel.o \
		settingsproxymodel.o \
		certificates.o \
		moc_settingsmodel.o \
		moc_imagesmodel.o \
		moc_settingsproxymodel.o \
		moc_certificates.o
DIST          = qml/plugins/example/example.qml \
		qml/plugins/example/example.json \
		qml/plugins/bluez4/bluez4.json \
		qml/plugins/bluez4/bluez4.qml \
		qml/plugins/developermode/developermode.qml \
		qml/plugins/developermode/developermode.json \
		qml/plugins/display/display.qml \
		qml/plugins/display/display.json \
		qml/plugins/wifi/wifi.qml \
		qml/plugins/wifi/wifi.json \
		qml/plugins/wifi/WifiSettings.qml \
		qml/plugins/wifi/WifiStatus.qml \
		qml/plugins/gps/gps.json \
		qml/plugins/gps/gps.svg \
		qml/plugins/gps/gps.qml \
		qml/components/SettingsColumn.qml \
		qml/plugins/language/language.qml \
		qml/plugins/language/language.json \
		qml/plugins/language/language.svg \
		translations/glacier-settings_en.ts \
		translations/glacier-settings_ru.ts \
		qml/plugins/about/about.qml \
		qml/plugins/about/about.json \
		qml/plugins/about/about.svg \
		qml/plugins/about/icon-glacier-icon.png \
		qml/plugins/about/magic.qml \
		qml/plugins/keyboard/keyboard.qml \
		qml/plugins/wifi/SavedServices.qml \
		qml/plugins/wifi/SavedStatus.qml \
		qml/plugins/wifi/NetworkDelegate.qml \
		qml/plugins/wifi/AddNetworkPage.qml \
		qml/plugins/wifi/SavedCertificates.qml \
		qml/plugins/wifi/AddCertificstePage.qml \
		/usr/share/qt5/mkspecs/features/spec_pre.prf \
		/usr/share/qt5/mkspecs/common/unix.conf \
		/usr/share/qt5/mkspecs/common/linux.conf \
		/usr/share/qt5/mkspecs/common/sanitize.conf \
		/usr/share/qt5/mkspecs/common/gcc-base.conf \
		/usr/share/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt5/mkspecs/common/g++-base.conf \
		/usr/share/qt5/mkspecs/common/g++-unix.conf \
		/usr/share/qt5/mkspecs/qconfig.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_compositor.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_compositor_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_contacts.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_contacts_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_docgallery.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_docgallery_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_feedback.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_feedback_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_organizer.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_organizer_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_publishsubscribe.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_publishsubscribe_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qmfclient.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qmfclient_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qmfmessageserver.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qmfmessageserver_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_serviceframework.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_serviceframework_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_versit.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_versit_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_versitorganizer.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_versitorganizer_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/share/qt5/mkspecs/features/qt_functions.prf \
		/usr/share/qt5/mkspecs/features/qt_config.prf \
		/usr/share/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/share/qt5/mkspecs/features/spec_post.prf \
		/usr/share/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt5/mkspecs/features/default_pre.prf \
		/usr/share/qt5/mkspecs/features/resolve_config.prf \
		/usr/share/qt5/mkspecs/features/default_post.prf \
		/usr/share/qt5/mkspecs/features/link_pkgconfig.prf \
		/usr/share/qt5/mkspecs/features/qml_debug.prf \
		/usr/share/qt5/mkspecs/features/warn_on.prf \
		/usr/share/qt5/mkspecs/features/qt.prf \
		/usr/share/qt5/mkspecs/features/resources.prf \
		/usr/share/qt5/mkspecs/features/moc.prf \
		/usr/share/qt5/mkspecs/features/unix/opengl.prf \
		/usr/share/qt5/mkspecs/features/unix/thread.prf \
		/usr/share/qt5/mkspecs/features/file_copies.prf \
		/usr/share/qt5/mkspecs/features/testcase_targets.prf \
		/usr/share/qt5/mkspecs/features/exceptions.prf \
		/usr/share/qt5/mkspecs/features/yacc.prf \
		/usr/share/qt5/mkspecs/features/lex.prf \
		glacier-settings.pro src/models/settingsmodel.h \
		src/models/imagesmodel.h \
		src/models/settingsproxymodel.h \
		certificates.h src/main.cpp \
		src/models/settingsmodel.cpp \
		src/models/imagesmodel.cpp \
		src/models/settingsproxymodel.cpp \
		certificates.cpp
QMAKE_TARGET  = glacier-settings
DESTDIR       = 
TARGET        = glacier-settings


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: glacier-settings.pro /usr/share/qt5/mkspecs/linux-g++/qmake.conf /usr/share/qt5/mkspecs/features/spec_pre.prf \
		/usr/share/qt5/mkspecs/common/unix.conf \
		/usr/share/qt5/mkspecs/common/linux.conf \
		/usr/share/qt5/mkspecs/common/sanitize.conf \
		/usr/share/qt5/mkspecs/common/gcc-base.conf \
		/usr/share/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt5/mkspecs/common/g++-base.conf \
		/usr/share/qt5/mkspecs/common/g++-unix.conf \
		/usr/share/qt5/mkspecs/qconfig.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_compositor.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_compositor_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_contacts.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_contacts_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_docgallery.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_docgallery_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_feedback.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_feedback_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_organizer.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_organizer_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_publishsubscribe.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_publishsubscribe_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qmfclient.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qmfclient_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qmfmessageserver.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qmfmessageserver_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_serviceframework.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_serviceframework_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_versit.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_versit_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_versitorganizer.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_versitorganizer_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/share/qt5/mkspecs/features/qt_functions.prf \
		/usr/share/qt5/mkspecs/features/qt_config.prf \
		/usr/share/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/share/qt5/mkspecs/features/spec_post.prf \
		/usr/share/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt5/mkspecs/features/default_pre.prf \
		/usr/share/qt5/mkspecs/features/resolve_config.prf \
		/usr/share/qt5/mkspecs/features/default_post.prf \
		/usr/share/qt5/mkspecs/features/link_pkgconfig.prf \
		/usr/share/qt5/mkspecs/features/qml_debug.prf \
		/usr/share/qt5/mkspecs/features/warn_on.prf \
		/usr/share/qt5/mkspecs/features/qt.prf \
		/usr/share/qt5/mkspecs/features/resources.prf \
		/usr/share/qt5/mkspecs/features/moc.prf \
		/usr/share/qt5/mkspecs/features/unix/opengl.prf \
		/usr/share/qt5/mkspecs/features/unix/thread.prf \
		/usr/share/qt5/mkspecs/features/file_copies.prf \
		/usr/share/qt5/mkspecs/features/testcase_targets.prf \
		/usr/share/qt5/mkspecs/features/exceptions.prf \
		/usr/share/qt5/mkspecs/features/yacc.prf \
		/usr/share/qt5/mkspecs/features/lex.prf \
		glacier-settings.pro \
		/usr/lib/libQt5Quick.prl \
		/usr/lib/libQt5Gui.prl \
		/usr/lib/libQt5Qml.prl \
		/usr/lib/libQt5Network.prl \
		/usr/lib/libQt5Core.prl
	$(QMAKE) 'QMAKE_CFLAGS_RELEASE=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -fmessage-length=0 -march=armv7-a -mfloat-abi=hard -mfpu=neon -mthumb -Wno-psabi' 'QMAKE_CFLAGS_DEBUG=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -fmessage-length=0 -march=armv7-a -mfloat-abi=hard -mfpu=neon -mthumb -Wno-psabi' 'QMAKE_CXXFLAGS_RELEASE=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -fmessage-length=0 -march=armv7-a -mfloat-abi=hard -mfpu=neon -mthumb -Wno-psabi' 'QMAKE_CXXFLAGS_DEBUG=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -fmessage-length=0 -march=armv7-a -mfloat-abi=hard -mfpu=neon -mthumb -Wno-psabi' QMAKE_STRIP=: PREFIX=/usr -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile glacier-settings.pro
/usr/share/qt5/mkspecs/features/spec_pre.prf:
/usr/share/qt5/mkspecs/common/unix.conf:
/usr/share/qt5/mkspecs/common/linux.conf:
/usr/share/qt5/mkspecs/common/sanitize.conf:
/usr/share/qt5/mkspecs/common/gcc-base.conf:
/usr/share/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt5/mkspecs/common/g++-base.conf:
/usr/share/qt5/mkspecs/common/g++-unix.conf:
/usr/share/qt5/mkspecs/qconfig.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_compositor.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_compositor_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_contacts.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_contacts_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_docgallery.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_docgallery_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_feedback.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_feedback_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_location.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_location_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_organizer.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_organizer_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_positioning.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_publishsubscribe.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_publishsubscribe_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_qmfclient.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_qmfclient_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_qmfmessageserver.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_qmfmessageserver_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_sensors.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_serviceframework.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_serviceframework_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_svg_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_versit.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_versit_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_versitorganizer.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_versitorganizer_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_waylandclient.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_webkit_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/share/qt5/mkspecs/features/qt_functions.prf:
/usr/share/qt5/mkspecs/features/qt_config.prf:
/usr/share/qt5/mkspecs/linux-g++/qmake.conf:
/usr/share/qt5/mkspecs/features/spec_post.prf:
/usr/share/qt5/mkspecs/features/exclusive_builds.prf:
/usr/share/qt5/mkspecs/features/default_pre.prf:
/usr/share/qt5/mkspecs/features/resolve_config.prf:
/usr/share/qt5/mkspecs/features/default_post.prf:
/usr/share/qt5/mkspecs/features/link_pkgconfig.prf:
/usr/share/qt5/mkspecs/features/qml_debug.prf:
/usr/share/qt5/mkspecs/features/warn_on.prf:
/usr/share/qt5/mkspecs/features/qt.prf:
/usr/share/qt5/mkspecs/features/resources.prf:
/usr/share/qt5/mkspecs/features/moc.prf:
/usr/share/qt5/mkspecs/features/unix/opengl.prf:
/usr/share/qt5/mkspecs/features/unix/thread.prf:
/usr/share/qt5/mkspecs/features/file_copies.prf:
/usr/share/qt5/mkspecs/features/testcase_targets.prf:
/usr/share/qt5/mkspecs/features/exceptions.prf:
/usr/share/qt5/mkspecs/features/yacc.prf:
/usr/share/qt5/mkspecs/features/lex.prf:
glacier-settings.pro:
/usr/lib/libQt5Quick.prl:
/usr/lib/libQt5Gui.prl:
/usr/lib/libQt5Qml.prl:
/usr/lib/libQt5Network.prl:
/usr/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) 'QMAKE_CFLAGS_RELEASE=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -fmessage-length=0 -march=armv7-a -mfloat-abi=hard -mfpu=neon -mthumb -Wno-psabi' 'QMAKE_CFLAGS_DEBUG=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -fmessage-length=0 -march=armv7-a -mfloat-abi=hard -mfpu=neon -mthumb -Wno-psabi' 'QMAKE_CXXFLAGS_RELEASE=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -fmessage-length=0 -march=armv7-a -mfloat-abi=hard -mfpu=neon -mthumb -Wno-psabi' 'QMAKE_CXXFLAGS_DEBUG=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -fmessage-length=0 -march=armv7-a -mfloat-abi=hard -mfpu=neon -mthumb -Wno-psabi' QMAKE_STRIP=: PREFIX=/usr -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile glacier-settings.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents src/models/settingsmodel.h src/models/imagesmodel.h src/models/settingsproxymodel.h certificates.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/models/settingsmodel.cpp src/models/imagesmodel.cpp src/models/settingsproxymodel.cpp certificates.cpp $(DISTDIR)/
	$(COPY_FILE) --parents translations/glacier-settings_en.ts translations/glacier-settings_ru.ts $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_settingsmodel.cpp moc_imagesmodel.cpp moc_settingsproxymodel.cpp moc_certificates.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_settingsmodel.cpp moc_imagesmodel.cpp moc_settingsproxymodel.cpp moc_certificates.cpp
moc_settingsmodel.cpp: src/models/settingsmodel.h
	/usr/lib/qt5/bin/moc $(DEFINES) -I/usr/share/qt5/mkspecs/linux-g++ -I/home/mersdk/share/nemo/settings/glacier-settings -I/usr/include/libglacierapp -I/usr/include/mdeclarativecache5 -I/usr/include/qt5 -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/opt/cross/armv7hl-meego-linux-gnueabi/include/c++/4.8.3 -I/opt/cross/armv7hl-meego-linux-gnueabi/include/c++/4.8.3/armv7hl-meego-linux-gnueabi -I/opt/cross/armv7hl-meego-linux-gnueabi/include/c++/4.8.3/backward -I/opt/cross/lib/gcc/armv7hl-meego-linux-gnueabi/4.8.3/include -I/usr/local/include -I/opt/cross/lib/gcc/armv7hl-meego-linux-gnueabi/4.8.3/include-fixed -I/opt/cross/armv7hl-meego-linux-gnueabi/include -I/usr/include src/models/settingsmodel.h -o moc_settingsmodel.cpp

moc_imagesmodel.cpp: src/models/imagesmodel.h
	/usr/lib/qt5/bin/moc $(DEFINES) -I/usr/share/qt5/mkspecs/linux-g++ -I/home/mersdk/share/nemo/settings/glacier-settings -I/usr/include/libglacierapp -I/usr/include/mdeclarativecache5 -I/usr/include/qt5 -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/opt/cross/armv7hl-meego-linux-gnueabi/include/c++/4.8.3 -I/opt/cross/armv7hl-meego-linux-gnueabi/include/c++/4.8.3/armv7hl-meego-linux-gnueabi -I/opt/cross/armv7hl-meego-linux-gnueabi/include/c++/4.8.3/backward -I/opt/cross/lib/gcc/armv7hl-meego-linux-gnueabi/4.8.3/include -I/usr/local/include -I/opt/cross/lib/gcc/armv7hl-meego-linux-gnueabi/4.8.3/include-fixed -I/opt/cross/armv7hl-meego-linux-gnueabi/include -I/usr/include src/models/imagesmodel.h -o moc_imagesmodel.cpp

moc_settingsproxymodel.cpp: src/models/settingsmodel.h \
		src/models/settingsproxymodel.h
	/usr/lib/qt5/bin/moc $(DEFINES) -I/usr/share/qt5/mkspecs/linux-g++ -I/home/mersdk/share/nemo/settings/glacier-settings -I/usr/include/libglacierapp -I/usr/include/mdeclarativecache5 -I/usr/include/qt5 -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/opt/cross/armv7hl-meego-linux-gnueabi/include/c++/4.8.3 -I/opt/cross/armv7hl-meego-linux-gnueabi/include/c++/4.8.3/armv7hl-meego-linux-gnueabi -I/opt/cross/armv7hl-meego-linux-gnueabi/include/c++/4.8.3/backward -I/opt/cross/lib/gcc/armv7hl-meego-linux-gnueabi/4.8.3/include -I/usr/local/include -I/opt/cross/lib/gcc/armv7hl-meego-linux-gnueabi/4.8.3/include-fixed -I/opt/cross/armv7hl-meego-linux-gnueabi/include -I/usr/include src/models/settingsproxymodel.h -o moc_settingsproxymodel.cpp

moc_certificates.cpp: certificates.h
	/usr/lib/qt5/bin/moc $(DEFINES) -I/usr/share/qt5/mkspecs/linux-g++ -I/home/mersdk/share/nemo/settings/glacier-settings -I/usr/include/libglacierapp -I/usr/include/mdeclarativecache5 -I/usr/include/qt5 -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/opt/cross/armv7hl-meego-linux-gnueabi/include/c++/4.8.3 -I/opt/cross/armv7hl-meego-linux-gnueabi/include/c++/4.8.3/armv7hl-meego-linux-gnueabi -I/opt/cross/armv7hl-meego-linux-gnueabi/include/c++/4.8.3/backward -I/opt/cross/lib/gcc/armv7hl-meego-linux-gnueabi/4.8.3/include -I/usr/local/include -I/opt/cross/lib/gcc/armv7hl-meego-linux-gnueabi/4.8.3/include-fixed -I/opt/cross/armv7hl-meego-linux-gnueabi/include -I/usr/include certificates.h -o moc_certificates.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: src/main.cpp src/models/settingsmodel.h \
		src/models/settingsproxymodel.h \
		certificates.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

settingsmodel.o: src/models/settingsmodel.cpp src/models/settingsmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settingsmodel.o src/models/settingsmodel.cpp

imagesmodel.o: src/models/imagesmodel.cpp src/models/imagesmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imagesmodel.o src/models/imagesmodel.cpp

settingsproxymodel.o: src/models/settingsproxymodel.cpp src/models/settingsproxymodel.h \
		src/models/settingsmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settingsproxymodel.o src/models/settingsproxymodel.cpp

certificates.o: certificates.cpp certificates.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o certificates.o certificates.cpp

moc_settingsmodel.o: moc_settingsmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_settingsmodel.o moc_settingsmodel.cpp

moc_imagesmodel.o: moc_imagesmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_imagesmodel.o moc_imagesmodel.cpp

moc_settingsproxymodel.o: moc_settingsproxymodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_settingsproxymodel.o moc_settingsproxymodel.cpp

moc_certificates.o: moc_certificates.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_certificates.o moc_certificates.cpp

####### Install

install_i18n_files: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/glacier-settings || mkdir -p $(INSTALL_ROOT)/usr/share/glacier-settings
	-$(INSTALL_DIR) /home/mersdk/share/nemo/settings/glacier-settings/translations $(INSTALL_ROOT)/usr/share/glacier-settings/

uninstall_i18n_files: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/glacier-settings/translations
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/glacier-settings/ 


install_target: first FORCE
	@test -d $(INSTALL_ROOT)/usr/bin || mkdir -p $(INSTALL_ROOT)/usr/bin
	-$(INSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/bin/ 


install_desktop: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/applications || mkdir -p $(INSTALL_ROOT)/usr/share/applications
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/glacier-settings.desktop $(INSTALL_ROOT)/usr/share/applications/

uninstall_desktop: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/applications/glacier-settings.desktop
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/applications/ 


install_qml: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/glacier-settings/qml || mkdir -p $(INSTALL_ROOT)/usr/share/glacier-settings/qml
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/qml/glacier-settings.qml $(INSTALL_ROOT)/usr/share/glacier-settings/qml/
	-$(INSTALL_DIR) /home/mersdk/share/nemo/settings/glacier-settings/qml/components $(INSTALL_ROOT)/usr/share/glacier-settings/qml/
	-$(INSTALL_DIR) /home/mersdk/share/nemo/settings/glacier-settings/qml/img $(INSTALL_ROOT)/usr/share/glacier-settings/qml/

uninstall_qml: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/glacier-settings/qml/img
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/glacier-settings/qml/components
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/glacier-settings/qml/glacier-settings.qml
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/glacier-settings/qml/ 


install_privileges: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/mapplauncherd/privileges.d/ || mkdir -p $(INSTALL_ROOT)/usr/share/mapplauncherd/privileges.d/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/glacier-settings.privileges $(INSTALL_ROOT)/usr/share/mapplauncherd/privileges.d/

uninstall_privileges: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/mapplauncherd/privileges.d/glacier-settings.privileges
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/mapplauncherd/privileges.d/ 


install_pluginconfigs: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/glacier-settings/plugins || mkdir -p $(INSTALL_ROOT)/usr/share/glacier-settings/plugins
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/qml/plugins/example/example.json $(INSTALL_ROOT)/usr/share/glacier-settings/plugins/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/qml/plugins/bluez4/bluez4.json $(INSTALL_ROOT)/usr/share/glacier-settings/plugins/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/qml/plugins/developermode/developermode.json $(INSTALL_ROOT)/usr/share/glacier-settings/plugins/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/qml/plugins/display/display.json $(INSTALL_ROOT)/usr/share/glacier-settings/plugins/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/qml/plugins/wifi/wifi.json $(INSTALL_ROOT)/usr/share/glacier-settings/plugins/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/qml/plugins/gps/gps.json $(INSTALL_ROOT)/usr/share/glacier-settings/plugins/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/qml/plugins/language/language.json $(INSTALL_ROOT)/usr/share/glacier-settings/plugins/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/qml/plugins/about/about.json $(INSTALL_ROOT)/usr/share/glacier-settings/plugins/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/qml/plugins/keyboard/keyboard.json $(INSTALL_ROOT)/usr/share/glacier-settings/plugins/

uninstall_pluginconfigs: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/glacier-settings/plugins/keyboard.json
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/glacier-settings/plugins/about.json
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/glacier-settings/plugins/language.json
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/glacier-settings/plugins/gps.json
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/glacier-settings/plugins/wifi.json
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/glacier-settings/plugins/display.json
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/glacier-settings/plugins/developermode.json
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/glacier-settings/plugins/bluez4.json
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/glacier-settings/plugins/example.json
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/glacier-settings/plugins/ 


install_exampleplugin: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/example || mkdir -p $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/example
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/qml/plugins/example/example.qml $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/example/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/qml/plugins/example/example.svg $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/example/

uninstall_exampleplugin: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/example/example.svg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/example/example.qml
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/example/ 


install_bluez4plugin: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/bluez4 || mkdir -p $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/bluez4
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/qml/plugins/bluez4/bluez4.qml $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/bluez4/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/qml/plugins/bluez4/bluez4.svg $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/bluez4/

uninstall_bluez4plugin: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/bluez4/bluez4.svg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/bluez4/bluez4.qml
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/bluez4/ 


install_developermodeplugin: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/developermode || mkdir -p $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/developermode
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/qml/plugins/developermode/developermode.qml $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/developermode/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/qml/plugins/developermode/developermode.svg $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/developermode/

uninstall_developermodeplugin: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/developermode/developermode.svg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/developermode/developermode.qml
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/developermode/ 


install_displayplugin: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/display || mkdir -p $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/display
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/qml/plugins/display/display.qml $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/display/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/qml/plugins/display/display.svg $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/display/

uninstall_displayplugin: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/display/display.svg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/display/display.qml
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/display/ 


install_wifiplugin: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/wifi || mkdir -p $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/wifi
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/qml/plugins/wifi/wifi.qml $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/wifi/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/qml/plugins/wifi/WifiSettings.qml $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/wifi/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/qml/plugins/wifi/WifiStatus.qml $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/wifi/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/qml/plugins/wifi/wifi.svg $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/wifi/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/qml/plugins/wifi/SavedServices.qml $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/wifi/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/qml/plugins/wifi/SavedStatus.qml $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/wifi/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/qml/plugins/wifi/NetworkDelegate.qml $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/wifi/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/qml/plugins/wifi/AddNetworkPage.qml $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/wifi/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/qml/plugins/wifi/SavedCertificates.qml $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/wifi/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/qml/plugins/wifi/AddCertificstePage.qml $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/wifi/

uninstall_wifiplugin: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/wifi/AddCertificstePage.qml
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/wifi/SavedCertificates.qml
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/wifi/AddNetworkPage.qml
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/wifi/NetworkDelegate.qml
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/wifi/SavedStatus.qml
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/wifi/SavedServices.qml
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/wifi/wifi.svg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/wifi/WifiStatus.qml
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/wifi/WifiSettings.qml
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/wifi/wifi.qml
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/wifi/ 


install_gpsplugin: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/gps || mkdir -p $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/gps
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/qml/plugins/gps/gps.qml $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/gps/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/qml/plugins/gps/gps.svg $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/gps/

uninstall_gpsplugin: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/gps/gps.svg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/gps/gps.qml
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/gps/ 


install_languageplugin: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/language || mkdir -p $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/language
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/qml/plugins/language/language.qml $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/language/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/qml/plugins/language/language.svg $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/language/

uninstall_languageplugin: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/language/language.svg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/language/language.qml
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/language/ 


install_aboutplugin: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/about || mkdir -p $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/about
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/qml/plugins/about/about.qml $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/about/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/qml/plugins/about/magic.qml $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/about/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/qml/plugins/about/about.svg $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/about/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/qml/plugins/about/bluecreature.svg $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/about/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/qml/plugins/about/icon-glacier-icon.png $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/about/

uninstall_aboutplugin: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/about/icon-glacier-icon.png
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/about/bluecreature.svg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/about/about.svg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/about/magic.qml
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/about/about.qml
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/about/ 


install_languageconfigs: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/jolla-supported-languages/ || mkdir -p $(INSTALL_ROOT)/usr/share/jolla-supported-languages/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/configs/supported-languages/bn.conf $(INSTALL_ROOT)/usr/share/jolla-supported-languages/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/configs/supported-languages/da.conf $(INSTALL_ROOT)/usr/share/jolla-supported-languages/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/configs/supported-languages/de.conf $(INSTALL_ROOT)/usr/share/jolla-supported-languages/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/configs/supported-languages/en_gb.conf $(INSTALL_ROOT)/usr/share/jolla-supported-languages/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/configs/supported-languages/en_us.conf $(INSTALL_ROOT)/usr/share/jolla-supported-languages/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/configs/supported-languages/es.conf $(INSTALL_ROOT)/usr/share/jolla-supported-languages/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/configs/supported-languages/fi.conf $(INSTALL_ROOT)/usr/share/jolla-supported-languages/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/configs/supported-languages/fr.conf $(INSTALL_ROOT)/usr/share/jolla-supported-languages/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/configs/supported-languages/gu.conf $(INSTALL_ROOT)/usr/share/jolla-supported-languages/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/configs/supported-languages/hi.conf $(INSTALL_ROOT)/usr/share/jolla-supported-languages/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/configs/supported-languages/it.conf $(INSTALL_ROOT)/usr/share/jolla-supported-languages/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/configs/supported-languages/kn.conf $(INSTALL_ROOT)/usr/share/jolla-supported-languages/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/configs/supported-languages/ml.conf $(INSTALL_ROOT)/usr/share/jolla-supported-languages/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/configs/supported-languages/mr.conf $(INSTALL_ROOT)/usr/share/jolla-supported-languages/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/configs/supported-languages/nb.conf $(INSTALL_ROOT)/usr/share/jolla-supported-languages/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/configs/supported-languages/pa.conf $(INSTALL_ROOT)/usr/share/jolla-supported-languages/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/configs/supported-languages/pl.conf $(INSTALL_ROOT)/usr/share/jolla-supported-languages/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/configs/supported-languages/pt.conf $(INSTALL_ROOT)/usr/share/jolla-supported-languages/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/configs/supported-languages/ru.conf $(INSTALL_ROOT)/usr/share/jolla-supported-languages/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/configs/supported-languages/sv.conf $(INSTALL_ROOT)/usr/share/jolla-supported-languages/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/configs/supported-languages/ta.conf $(INSTALL_ROOT)/usr/share/jolla-supported-languages/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/configs/supported-languages/te.conf $(INSTALL_ROOT)/usr/share/jolla-supported-languages/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/configs/supported-languages/tt.conf $(INSTALL_ROOT)/usr/share/jolla-supported-languages/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/configs/supported-languages/zh_cn.conf $(INSTALL_ROOT)/usr/share/jolla-supported-languages/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/configs/supported-languages/zh_hk.conf $(INSTALL_ROOT)/usr/share/jolla-supported-languages/

uninstall_languageconfigs: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/jolla-supported-languages/zh_hk.conf
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/jolla-supported-languages/zh_cn.conf
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/jolla-supported-languages/tt.conf
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/jolla-supported-languages/te.conf
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/jolla-supported-languages/ta.conf
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/jolla-supported-languages/sv.conf
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/jolla-supported-languages/ru.conf
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/jolla-supported-languages/pt.conf
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/jolla-supported-languages/pl.conf
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/jolla-supported-languages/pa.conf
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/jolla-supported-languages/nb.conf
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/jolla-supported-languages/mr.conf
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/jolla-supported-languages/ml.conf
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/jolla-supported-languages/kn.conf
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/jolla-supported-languages/it.conf
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/jolla-supported-languages/hi.conf
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/jolla-supported-languages/gu.conf
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/jolla-supported-languages/fr.conf
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/jolla-supported-languages/fi.conf
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/jolla-supported-languages/es.conf
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/jolla-supported-languages/en_us.conf
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/jolla-supported-languages/en_gb.conf
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/jolla-supported-languages/de.conf
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/jolla-supported-languages/da.conf
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/jolla-supported-languages/bn.conf
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/jolla-supported-languages/ 


install_icon: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/glacier-settings/ || mkdir -p $(INSTALL_ROOT)/usr/share/glacier-settings/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/glacier-settings.png $(INSTALL_ROOT)/usr/share/glacier-settings/

uninstall_icon: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/glacier-settings/glacier-settings.png
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/glacier-settings/ 


install_keyboardplugin: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/keyboard || mkdir -p $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/keyboard
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/qml/plugins/keyboard/keyboard.qml $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/keyboard/
	-$(INSTALL_FILE) /home/mersdk/share/nemo/settings/glacier-settings/qml/plugins/keyboard/keyboard.svg $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/keyboard/

uninstall_keyboardplugin: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/keyboard/keyboard.svg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/keyboard/keyboard.qml
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/glacier-settings/qml/plugins/keyboard/ 


install: install_i18n_files install_target install_desktop install_qml install_privileges install_pluginconfigs install_exampleplugin install_bluez4plugin install_developermodeplugin install_displayplugin install_wifiplugin install_gpsplugin install_languageplugin install_aboutplugin install_languageconfigs install_icon install_keyboardplugin  FORCE

uninstall: uninstall_i18n_files uninstall_target uninstall_desktop uninstall_qml uninstall_privileges uninstall_pluginconfigs uninstall_exampleplugin uninstall_bluez4plugin uninstall_developermodeplugin uninstall_displayplugin uninstall_wifiplugin uninstall_gpsplugin uninstall_languageplugin uninstall_aboutplugin uninstall_languageconfigs uninstall_icon uninstall_keyboardplugin  FORCE

FORCE:

